services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=symon
      - POSTGRES_PASSWORD=symon123456789
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
